baseURL = "https://yhmayyds.group/"
title = "Research Group of Yuhan Ma"

languageCode = "zh-cn"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
removePathAccents = true

[module]
proxy = "https://goproxy.cn"

[[module.imports]]
# disable = false
# ignoreConfig = false
# ignoreImports = false
path = 'github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5'
# [[module.imports]]
# path = 'github.com/wowchemy/starter-hugo-research-group'
# [[module.imports]]
# path = 'github.com/wowchemy/starter-hugo-academic'

# [[module.mounts]]
# source = "content/publication"
# target = "content/en/publication"
# lang = "en"
# [[module.mounts]]
# source = "content/publication"
# target = "content/zh/publication"
# lang = "zh"

[security]
_merge = "deep"
[sitemap]
_merge = "deep"
[minify]
_merge = "deep"
