title: 'yhma lab'
org_name: 'Yuhan Ma Lab'

baseURL: 'https://yhmayyds.group/'
languageCode: 'en-US'
defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: false

hasCJKLanguage: true
enableRobotsTXT: true
enableEmoji: true
removePathAccents: true

build:
  writeStats: true

markup:
  goldmark:
    extensions:
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      strikethrough: false
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: true
    style: monokai
    tabWidth: 4

security:
  _merge: 'deep'
sitemap:
  _merge: 'deep'
minify:
  _merge: 'deep'
