# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: L

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  widget: minimal
  copyright:
    notice: "© {year} Yuhan Ma. This site is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  # For multilingual sites, show a language chooser in the footer?
  # show_translations: true

# Localization

locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"
  address_format: en-us

# Site features

features:
  # syntax_highlighter:
  #   theme_light: github-light
  #   theme_dark: dracula
  math:
    enable: false
  repository:
    url: "https://github.com/lqhuang/yhma-group-yyds"
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  search:
    provider: wowchemy

# Extensions

extensions:
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

# SEO

marketing:
  seo:
    site_type: Person
    # local_business_type: "" # https://schema.org/LocalBusiness#subtypes
    org_name: "Beijing Normal University"
    description:
      "Yuhan Ma's personal resume and detail infomation about his research group"
  verification:
    google: ""
    baidu: ""
    bing: ""
  google_optimize:
